=== jiuce/Core-Java/File Input-Output_DataConversionDBand XML/catalog.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!ELEMENT CATEGORY (PRODUCT+)>
<!ELEMENT PRODUCT (PID, PNAME, PDESCRIPTION, PPRICE, PDISCOUNT)>
<!ELEMENT PID (#PCDATA)>
<!ELEMENT PNAME (#PCDATA)>
<!ELEMENT PDESCRIPTION (#PCDATA)>
<!ELEMENT PPRICE (#PCDATA)>
<!ELEMENT PDISCOUNT (#PCDATA)>

=== jiuce/Core-Java/File Input-Output_DataConversionDBand XML/NewFile.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE CATEGORY SYSTEM "catalog.dtd" >
<CATEGORY>
  <PRODUCT>
    <PID>101</PID>
    <PNAME>AAA</PNAME>
    <PDESCRIPTION>BSFBFDBFDBFD</PDESCRIPTION>
    <PPRICE>222223</PPRICE>
    <PDISCOUNT>10%</PDISCOUNT>
  </PRODUCT>
  <PRODUCT>
    <PID>102</PID>
    <PNAME>AfA</PNAME>
    <PDESCRIPTION>BSFBFDBFggDBFD</PDESCRIPTION>
    <PPRICE>22223</PPRICE>
    <PDISCOUNT>10%</PDISCOUNT>
  </PRODUCT>
</CATEGORY>
