<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE CATEGORY[
<!ELEMENT CATALOG (CATEGORY+)>
<!ELEMENT CATEGORY (PRODUCT+)>
<!ELEMENT PRODUCT (PNAME, PDESCRIPTION, PPRICE, PDISCOUNT)>
<!ELEMENT PNAME (#PCDATA)>
<!ELEMENT PDESCRIPTION (#PCDATA)>
<!ELEMENT PPRICE (#PCDATA)>
<!ELEMENT PDISCOUNT (#PCDATA)>
<!ATTLIST CATEGORY Category (ELECTRONICS|OTHERS) #REQUIRED>
<!ATTLIST PRODUCT PID ID #REQUIRED>
]>

<CATALOG>
<CATEGORY Category="ELECTRONICS">
  <PRODUCT PID="SDD1">
    <PNAME>AAA</PNAME>
    <PDESCRIPTION>BSFBFDBFDBFD</PDESCRIPTION>
    <PPRICE>222223</PPRICE>
    <PDISCOUNT>10%</PDISCOUNT>
  </PRODUCT>
  <PRODUCT PID="SDD2">
    <PNAME>AfA</PNAME>
    <PDESCRIPTION>BSFBFDBFggDBFD</PDESCRIPTION>
    <PPRICE>22223</PPRICE>
    <PDISCOUNT>10%</PDISCOUNT>
  </PRODUCT>
</CATEGORY>
<CATEGORY Category="OTHERS">
  <PRODUCT PID="OTT1">
    <PNAME>SSS</PNAME>
    <PDESCRIPTION>BNLNL/BFDBFD</PDESCRIPTION>
    <PPRICE>22</PPRICE>
    <PDISCOUNT>5%</PDISCOUNT>
  </PRODUCT>
  </CATEGORY>
</CATALOG>